// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

/**
 * <pre>
 * 获取聊天历史响应
 * </pre>
 *
 * Protobuf type {@code com.bdsw.msg.GetChatHistoryResponse}
 */
@com.google.protobuf.Generated
public final class GetChatHistoryResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bdsw.msg.GetChatHistoryResponse)
    GetChatHistoryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      GetChatHistoryResponse.class.getName());
  }
  // Use GetChatHistoryResponse.newBuilder() to construct.
  private GetChatHistoryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetChatHistoryResponse() {
    messages_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_GetChatHistoryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_GetChatHistoryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bdsw.msg.GetChatHistoryResponse.class, com.bdsw.msg.GetChatHistoryResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_FIELD_NUMBER = 1;
  private com.bdsw.common.BaseResponse base_;
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return Whether the base field is set.
   */
  @java.lang.Override
  public boolean hasBase() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return The base.
   */
  @java.lang.Override
  public com.bdsw.common.BaseResponse getBase() {
    return base_ == null ? com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
  }
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   */
  @java.lang.Override
  public com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder() {
    return base_ == null ? com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
  }

  public static final int MESSAGES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.bdsw.common.ServerMessage> messages_;
  /**
   * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.bdsw.common.ServerMessage> getMessagesList() {
    return messages_;
  }
  /**
   * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.bdsw.common.ServerMessageOrBuilder> 
      getMessagesOrBuilderList() {
    return messages_;
  }
  /**
   * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
   */
  @java.lang.Override
  public int getMessagesCount() {
    return messages_.size();
  }
  /**
   * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
   */
  @java.lang.Override
  public com.bdsw.common.ServerMessage getMessages(int index) {
    return messages_.get(index);
  }
  /**
   * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
   */
  @java.lang.Override
  public com.bdsw.common.ServerMessageOrBuilder getMessagesOrBuilder(
      int index) {
    return messages_.get(index);
  }

  public static final int PAGE_FIELD_NUMBER = 3;
  private com.bdsw.common.PageResponse page_;
  /**
   * <code>.com.bdsw.common.PageResponse page = 3;</code>
   * @return Whether the page field is set.
   */
  @java.lang.Override
  public boolean hasPage() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.com.bdsw.common.PageResponse page = 3;</code>
   * @return The page.
   */
  @java.lang.Override
  public com.bdsw.common.PageResponse getPage() {
    return page_ == null ? com.bdsw.common.PageResponse.getDefaultInstance() : page_;
  }
  /**
   * <code>.com.bdsw.common.PageResponse page = 3;</code>
   */
  @java.lang.Override
  public com.bdsw.common.PageResponseOrBuilder getPageOrBuilder() {
    return page_ == null ? com.bdsw.common.PageResponse.getDefaultInstance() : page_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBase());
    }
    for (int i = 0; i < messages_.size(); i++) {
      output.writeMessage(2, messages_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getPage());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBase());
    }
    for (int i = 0; i < messages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, messages_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPage());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bdsw.msg.GetChatHistoryResponse)) {
      return super.equals(obj);
    }
    com.bdsw.msg.GetChatHistoryResponse other = (com.bdsw.msg.GetChatHistoryResponse) obj;

    if (hasBase() != other.hasBase()) return false;
    if (hasBase()) {
      if (!getBase()
          .equals(other.getBase())) return false;
    }
    if (!getMessagesList()
        .equals(other.getMessagesList())) return false;
    if (hasPage() != other.hasPage()) return false;
    if (hasPage()) {
      if (!getPage()
          .equals(other.getPage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBase()) {
      hash = (37 * hash) + BASE_FIELD_NUMBER;
      hash = (53 * hash) + getBase().hashCode();
    }
    if (getMessagesCount() > 0) {
      hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getMessagesList().hashCode();
    }
    if (hasPage()) {
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bdsw.msg.GetChatHistoryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.GetChatHistoryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.GetChatHistoryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.GetChatHistoryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.GetChatHistoryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.GetChatHistoryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.GetChatHistoryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.msg.GetChatHistoryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bdsw.msg.GetChatHistoryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bdsw.msg.GetChatHistoryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bdsw.msg.GetChatHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.msg.GetChatHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bdsw.msg.GetChatHistoryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 获取聊天历史响应
   * </pre>
   *
   * Protobuf type {@code com.bdsw.msg.GetChatHistoryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bdsw.msg.GetChatHistoryResponse)
      com.bdsw.msg.GetChatHistoryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_GetChatHistoryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_GetChatHistoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bdsw.msg.GetChatHistoryResponse.class, com.bdsw.msg.GetChatHistoryResponse.Builder.class);
    }

    // Construct using com.bdsw.msg.GetChatHistoryResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBaseFieldBuilder();
        internalGetMessagesFieldBuilder();
        internalGetPageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      base_ = null;
      if (baseBuilder_ != null) {
        baseBuilder_.dispose();
        baseBuilder_ = null;
      }
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
      } else {
        messages_ = null;
        messagesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      page_ = null;
      if (pageBuilder_ != null) {
        pageBuilder_.dispose();
        pageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_GetChatHistoryResponse_descriptor;
    }

    @java.lang.Override
    public com.bdsw.msg.GetChatHistoryResponse getDefaultInstanceForType() {
      return com.bdsw.msg.GetChatHistoryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bdsw.msg.GetChatHistoryResponse build() {
      com.bdsw.msg.GetChatHistoryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bdsw.msg.GetChatHistoryResponse buildPartial() {
      com.bdsw.msg.GetChatHistoryResponse result = new com.bdsw.msg.GetChatHistoryResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.bdsw.msg.GetChatHistoryResponse result) {
      if (messagesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.messages_ = messages_;
      } else {
        result.messages_ = messagesBuilder_.build();
      }
    }

    private void buildPartial0(com.bdsw.msg.GetChatHistoryResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.base_ = baseBuilder_ == null
            ? base_
            : baseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.page_ = pageBuilder_ == null
            ? page_
            : pageBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bdsw.msg.GetChatHistoryResponse) {
        return mergeFrom((com.bdsw.msg.GetChatHistoryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bdsw.msg.GetChatHistoryResponse other) {
      if (other == com.bdsw.msg.GetChatHistoryResponse.getDefaultInstance()) return this;
      if (other.hasBase()) {
        mergeBase(other.getBase());
      }
      if (messagesBuilder_ == null) {
        if (!other.messages_.isEmpty()) {
          if (messages_.isEmpty()) {
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMessagesIsMutable();
            messages_.addAll(other.messages_);
          }
          onChanged();
        }
      } else {
        if (!other.messages_.isEmpty()) {
          if (messagesBuilder_.isEmpty()) {
            messagesBuilder_.dispose();
            messagesBuilder_ = null;
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000002);
            messagesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetMessagesFieldBuilder() : null;
          } else {
            messagesBuilder_.addAllMessages(other.messages_);
          }
        }
      }
      if (other.hasPage()) {
        mergePage(other.getPage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBaseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.bdsw.common.ServerMessage m =
                  input.readMessage(
                      com.bdsw.common.ServerMessage.parser(),
                      extensionRegistry);
              if (messagesBuilder_ == null) {
                ensureMessagesIsMutable();
                messages_.add(m);
              } else {
                messagesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetPageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.bdsw.common.BaseResponse base_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bdsw.common.BaseResponse, com.bdsw.common.BaseResponse.Builder, com.bdsw.common.BaseResponseOrBuilder> baseBuilder_;
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     * @return Whether the base field is set.
     */
    public boolean hasBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     * @return The base.
     */
    public com.bdsw.common.BaseResponse getBase() {
      if (baseBuilder_ == null) {
        return base_ == null ? com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
      } else {
        return baseBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder setBase(com.bdsw.common.BaseResponse value) {
      if (baseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        base_ = value;
      } else {
        baseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder setBase(
        com.bdsw.common.BaseResponse.Builder builderForValue) {
      if (baseBuilder_ == null) {
        base_ = builderForValue.build();
      } else {
        baseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder mergeBase(com.bdsw.common.BaseResponse value) {
      if (baseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          base_ != null &&
          base_ != com.bdsw.common.BaseResponse.getDefaultInstance()) {
          getBaseBuilder().mergeFrom(value);
        } else {
          base_ = value;
        }
      } else {
        baseBuilder_.mergeFrom(value);
      }
      if (base_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder clearBase() {
      bitField0_ = (bitField0_ & ~0x00000001);
      base_ = null;
      if (baseBuilder_ != null) {
        baseBuilder_.dispose();
        baseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public com.bdsw.common.BaseResponse.Builder getBaseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBaseFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder() {
      if (baseBuilder_ != null) {
        return baseBuilder_.getMessageOrBuilder();
      } else {
        return base_ == null ?
            com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
      }
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bdsw.common.BaseResponse, com.bdsw.common.BaseResponse.Builder, com.bdsw.common.BaseResponseOrBuilder> 
        internalGetBaseFieldBuilder() {
      if (baseBuilder_ == null) {
        baseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bdsw.common.BaseResponse, com.bdsw.common.BaseResponse.Builder, com.bdsw.common.BaseResponseOrBuilder>(
                getBase(),
                getParentForChildren(),
                isClean());
        base_ = null;
      }
      return baseBuilder_;
    }

    private java.util.List<com.bdsw.common.ServerMessage> messages_ =
      java.util.Collections.emptyList();
    private void ensureMessagesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        messages_ = new java.util.ArrayList<com.bdsw.common.ServerMessage>(messages_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bdsw.common.ServerMessage, com.bdsw.common.ServerMessage.Builder, com.bdsw.common.ServerMessageOrBuilder> messagesBuilder_;

    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public java.util.List<com.bdsw.common.ServerMessage> getMessagesList() {
      if (messagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messages_);
      } else {
        return messagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public int getMessagesCount() {
      if (messagesBuilder_ == null) {
        return messages_.size();
      } else {
        return messagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public com.bdsw.common.ServerMessage getMessages(int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);
      } else {
        return messagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public Builder setMessages(
        int index, com.bdsw.common.ServerMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.set(index, value);
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public Builder setMessages(
        int index, com.bdsw.common.ServerMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.set(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public Builder addMessages(com.bdsw.common.ServerMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public Builder addMessages(
        int index, com.bdsw.common.ServerMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(index, value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public Builder addMessages(
        com.bdsw.common.ServerMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public Builder addMessages(
        int index, com.bdsw.common.ServerMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public Builder addAllMessages(
        java.lang.Iterable<? extends com.bdsw.common.ServerMessage> values) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messages_);
        onChanged();
      } else {
        messagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public Builder clearMessages() {
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        messagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public Builder removeMessages(int index) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.remove(index);
        onChanged();
      } else {
        messagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public com.bdsw.common.ServerMessage.Builder getMessagesBuilder(
        int index) {
      return internalGetMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public com.bdsw.common.ServerMessageOrBuilder getMessagesOrBuilder(
        int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);  } else {
        return messagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public java.util.List<? extends com.bdsw.common.ServerMessageOrBuilder> 
         getMessagesOrBuilderList() {
      if (messagesBuilder_ != null) {
        return messagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messages_);
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public com.bdsw.common.ServerMessage.Builder addMessagesBuilder() {
      return internalGetMessagesFieldBuilder().addBuilder(
          com.bdsw.common.ServerMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public com.bdsw.common.ServerMessage.Builder addMessagesBuilder(
        int index) {
      return internalGetMessagesFieldBuilder().addBuilder(
          index, com.bdsw.common.ServerMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
     */
    public java.util.List<com.bdsw.common.ServerMessage.Builder> 
         getMessagesBuilderList() {
      return internalGetMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bdsw.common.ServerMessage, com.bdsw.common.ServerMessage.Builder, com.bdsw.common.ServerMessageOrBuilder> 
        internalGetMessagesFieldBuilder() {
      if (messagesBuilder_ == null) {
        messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bdsw.common.ServerMessage, com.bdsw.common.ServerMessage.Builder, com.bdsw.common.ServerMessageOrBuilder>(
                messages_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        messages_ = null;
      }
      return messagesBuilder_;
    }

    private com.bdsw.common.PageResponse page_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bdsw.common.PageResponse, com.bdsw.common.PageResponse.Builder, com.bdsw.common.PageResponseOrBuilder> pageBuilder_;
    /**
     * <code>.com.bdsw.common.PageResponse page = 3;</code>
     * @return Whether the page field is set.
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.com.bdsw.common.PageResponse page = 3;</code>
     * @return The page.
     */
    public com.bdsw.common.PageResponse getPage() {
      if (pageBuilder_ == null) {
        return page_ == null ? com.bdsw.common.PageResponse.getDefaultInstance() : page_;
      } else {
        return pageBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.bdsw.common.PageResponse page = 3;</code>
     */
    public Builder setPage(com.bdsw.common.PageResponse value) {
      if (pageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        page_ = value;
      } else {
        pageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.PageResponse page = 3;</code>
     */
    public Builder setPage(
        com.bdsw.common.PageResponse.Builder builderForValue) {
      if (pageBuilder_ == null) {
        page_ = builderForValue.build();
      } else {
        pageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.PageResponse page = 3;</code>
     */
    public Builder mergePage(com.bdsw.common.PageResponse value) {
      if (pageBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          page_ != null &&
          page_ != com.bdsw.common.PageResponse.getDefaultInstance()) {
          getPageBuilder().mergeFrom(value);
        } else {
          page_ = value;
        }
      } else {
        pageBuilder_.mergeFrom(value);
      }
      if (page_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.bdsw.common.PageResponse page = 3;</code>
     */
    public Builder clearPage() {
      bitField0_ = (bitField0_ & ~0x00000004);
      page_ = null;
      if (pageBuilder_ != null) {
        pageBuilder_.dispose();
        pageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.PageResponse page = 3;</code>
     */
    public com.bdsw.common.PageResponse.Builder getPageBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetPageFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.bdsw.common.PageResponse page = 3;</code>
     */
    public com.bdsw.common.PageResponseOrBuilder getPageOrBuilder() {
      if (pageBuilder_ != null) {
        return pageBuilder_.getMessageOrBuilder();
      } else {
        return page_ == null ?
            com.bdsw.common.PageResponse.getDefaultInstance() : page_;
      }
    }
    /**
     * <code>.com.bdsw.common.PageResponse page = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bdsw.common.PageResponse, com.bdsw.common.PageResponse.Builder, com.bdsw.common.PageResponseOrBuilder> 
        internalGetPageFieldBuilder() {
      if (pageBuilder_ == null) {
        pageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bdsw.common.PageResponse, com.bdsw.common.PageResponse.Builder, com.bdsw.common.PageResponseOrBuilder>(
                getPage(),
                getParentForChildren(),
                isClean());
        page_ = null;
      }
      return pageBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.bdsw.msg.GetChatHistoryResponse)
  }

  // @@protoc_insertion_point(class_scope:com.bdsw.msg.GetChatHistoryResponse)
  private static final com.bdsw.msg.GetChatHistoryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bdsw.msg.GetChatHistoryResponse();
  }

  public static com.bdsw.msg.GetChatHistoryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetChatHistoryResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetChatHistoryResponse>() {
    @java.lang.Override
    public GetChatHistoryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetChatHistoryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetChatHistoryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bdsw.msg.GetChatHistoryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

