// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

@com.google.protobuf.Generated
public interface GetChatHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.msg.GetChatHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return The base.
   */
  com.bdsw.common.BaseResponse getBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   */
  com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder();

  /**
   * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
   */
  java.util.List<com.bdsw.common.ServerMessage> 
      getMessagesList();
  /**
   * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
   */
  com.bdsw.common.ServerMessage getMessages(int index);
  /**
   * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
   */
  java.util.List<? extends com.bdsw.common.ServerMessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .com.bdsw.common.ServerMessage messages = 2;</code>
   */
  com.bdsw.common.ServerMessageOrBuilder getMessagesOrBuilder(
      int index);

  /**
   * <code>.com.bdsw.common.PageResponse page = 3;</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>.com.bdsw.common.PageResponse page = 3;</code>
   * @return The page.
   */
  com.bdsw.common.PageResponse getPage();
  /**
   * <code>.com.bdsw.common.PageResponse page = 3;</code>
   */
  com.bdsw.common.PageResponseOrBuilder getPageOrBuilder();
}
