// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

@com.google.protobuf.Generated
public interface GetChatHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.msg.GetChatHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>int64 start_time = 3;</code>
   * @return The startTime.
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 4;</code>
   * @return The endTime.
   */
  long getEndTime();

  /**
   * <code>.com.bdsw.common.PageRequest page = 5;</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>.com.bdsw.common.PageRequest page = 5;</code>
   * @return The page.
   */
  com.bdsw.common.PageRequest getPage();
  /**
   * <code>.com.bdsw.common.PageRequest page = 5;</code>
   */
  com.bdsw.common.PageRequestOrBuilder getPageOrBuilder();
}
