// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

@com.google.protobuf.Generated
public interface GetUserSessionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.msg.GetUserSessionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>.com.bdsw.common.PageRequest page = 2;</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>.com.bdsw.common.PageRequest page = 2;</code>
   * @return The page.
   */
  com.bdsw.common.PageRequest getPage();
  /**
   * <code>.com.bdsw.common.PageRequest page = 2;</code>
   */
  com.bdsw.common.PageRequestOrBuilder getPageOrBuilder();
}
