// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

@com.google.protobuf.Generated
public interface GetUserSessionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.msg.GetUserSessionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return The base.
   */
  com.bdsw.common.BaseResponse getBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   */
  com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder();

  /**
   * <code>repeated .com.bdsw.msg.SessionInfo sessions = 2;</code>
   */
  java.util.List<com.bdsw.msg.SessionInfo> 
      getSessionsList();
  /**
   * <code>repeated .com.bdsw.msg.SessionInfo sessions = 2;</code>
   */
  com.bdsw.msg.SessionInfo getSessions(int index);
  /**
   * <code>repeated .com.bdsw.msg.SessionInfo sessions = 2;</code>
   */
  int getSessionsCount();
  /**
   * <code>repeated .com.bdsw.msg.SessionInfo sessions = 2;</code>
   */
  java.util.List<? extends com.bdsw.msg.SessionInfoOrBuilder> 
      getSessionsOrBuilderList();
  /**
   * <code>repeated .com.bdsw.msg.SessionInfo sessions = 2;</code>
   */
  com.bdsw.msg.SessionInfoOrBuilder getSessionsOrBuilder(
      int index);

  /**
   * <code>.com.bdsw.common.PageResponse page = 3;</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>.com.bdsw.common.PageResponse page = 3;</code>
   * @return The page.
   */
  com.bdsw.common.PageResponse getPage();
  /**
   * <code>.com.bdsw.common.PageResponse page = 3;</code>
   */
  com.bdsw.common.PageResponseOrBuilder getPageOrBuilder();
}
