// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

/**
 * <pre>
 * 处理批量消息响应
 * </pre>
 *
 * Protobuf type {@code com.bdsw.msg.HandleBatchMessagesResponse}
 */
@com.google.protobuf.Generated
public final class HandleBatchMessagesResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bdsw.msg.HandleBatchMessagesResponse)
    HandleBatchMessagesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      HandleBatchMessagesResponse.class.getName());
  }
  // Use HandleBatchMessagesResponse.newBuilder() to construct.
  private HandleBatchMessagesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HandleBatchMessagesResponse() {
    responses_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_HandleBatchMessagesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_HandleBatchMessagesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bdsw.msg.HandleBatchMessagesResponse.class, com.bdsw.msg.HandleBatchMessagesResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_FIELD_NUMBER = 1;
  private com.bdsw.common.BaseResponse base_;
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return Whether the base field is set.
   */
  @java.lang.Override
  public boolean hasBase() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return The base.
   */
  @java.lang.Override
  public com.bdsw.common.BaseResponse getBase() {
    return base_ == null ? com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
  }
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   */
  @java.lang.Override
  public com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder() {
    return base_ == null ? com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
  }

  public static final int RESPONSES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.bdsw.common.ServerMessage> responses_;
  /**
   * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.bdsw.common.ServerMessage> getResponsesList() {
    return responses_;
  }
  /**
   * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.bdsw.common.ServerMessageOrBuilder> 
      getResponsesOrBuilderList() {
    return responses_;
  }
  /**
   * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
   */
  @java.lang.Override
  public int getResponsesCount() {
    return responses_.size();
  }
  /**
   * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
   */
  @java.lang.Override
  public com.bdsw.common.ServerMessage getResponses(int index) {
    return responses_.get(index);
  }
  /**
   * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
   */
  @java.lang.Override
  public com.bdsw.common.ServerMessageOrBuilder getResponsesOrBuilder(
      int index) {
    return responses_.get(index);
  }

  public static final int SUCCESS_COUNT_FIELD_NUMBER = 3;
  private int successCount_ = 0;
  /**
   * <code>int32 success_count = 3;</code>
   * @return The successCount.
   */
  @java.lang.Override
  public int getSuccessCount() {
    return successCount_;
  }

  public static final int FAIL_COUNT_FIELD_NUMBER = 4;
  private int failCount_ = 0;
  /**
   * <code>int32 fail_count = 4;</code>
   * @return The failCount.
   */
  @java.lang.Override
  public int getFailCount() {
    return failCount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBase());
    }
    for (int i = 0; i < responses_.size(); i++) {
      output.writeMessage(2, responses_.get(i));
    }
    if (successCount_ != 0) {
      output.writeInt32(3, successCount_);
    }
    if (failCount_ != 0) {
      output.writeInt32(4, failCount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBase());
    }
    for (int i = 0; i < responses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, responses_.get(i));
    }
    if (successCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, successCount_);
    }
    if (failCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, failCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bdsw.msg.HandleBatchMessagesResponse)) {
      return super.equals(obj);
    }
    com.bdsw.msg.HandleBatchMessagesResponse other = (com.bdsw.msg.HandleBatchMessagesResponse) obj;

    if (hasBase() != other.hasBase()) return false;
    if (hasBase()) {
      if (!getBase()
          .equals(other.getBase())) return false;
    }
    if (!getResponsesList()
        .equals(other.getResponsesList())) return false;
    if (getSuccessCount()
        != other.getSuccessCount()) return false;
    if (getFailCount()
        != other.getFailCount()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBase()) {
      hash = (37 * hash) + BASE_FIELD_NUMBER;
      hash = (53 * hash) + getBase().hashCode();
    }
    if (getResponsesCount() > 0) {
      hash = (37 * hash) + RESPONSES_FIELD_NUMBER;
      hash = (53 * hash) + getResponsesList().hashCode();
    }
    hash = (37 * hash) + SUCCESS_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getSuccessCount();
    hash = (37 * hash) + FAIL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getFailCount();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bdsw.msg.HandleBatchMessagesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.HandleBatchMessagesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.HandleBatchMessagesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.HandleBatchMessagesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.HandleBatchMessagesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.HandleBatchMessagesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.HandleBatchMessagesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.msg.HandleBatchMessagesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bdsw.msg.HandleBatchMessagesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bdsw.msg.HandleBatchMessagesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bdsw.msg.HandleBatchMessagesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.msg.HandleBatchMessagesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bdsw.msg.HandleBatchMessagesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 处理批量消息响应
   * </pre>
   *
   * Protobuf type {@code com.bdsw.msg.HandleBatchMessagesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bdsw.msg.HandleBatchMessagesResponse)
      com.bdsw.msg.HandleBatchMessagesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_HandleBatchMessagesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_HandleBatchMessagesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bdsw.msg.HandleBatchMessagesResponse.class, com.bdsw.msg.HandleBatchMessagesResponse.Builder.class);
    }

    // Construct using com.bdsw.msg.HandleBatchMessagesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBaseFieldBuilder();
        internalGetResponsesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      base_ = null;
      if (baseBuilder_ != null) {
        baseBuilder_.dispose();
        baseBuilder_ = null;
      }
      if (responsesBuilder_ == null) {
        responses_ = java.util.Collections.emptyList();
      } else {
        responses_ = null;
        responsesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      successCount_ = 0;
      failCount_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_HandleBatchMessagesResponse_descriptor;
    }

    @java.lang.Override
    public com.bdsw.msg.HandleBatchMessagesResponse getDefaultInstanceForType() {
      return com.bdsw.msg.HandleBatchMessagesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bdsw.msg.HandleBatchMessagesResponse build() {
      com.bdsw.msg.HandleBatchMessagesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bdsw.msg.HandleBatchMessagesResponse buildPartial() {
      com.bdsw.msg.HandleBatchMessagesResponse result = new com.bdsw.msg.HandleBatchMessagesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.bdsw.msg.HandleBatchMessagesResponse result) {
      if (responsesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          responses_ = java.util.Collections.unmodifiableList(responses_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.responses_ = responses_;
      } else {
        result.responses_ = responsesBuilder_.build();
      }
    }

    private void buildPartial0(com.bdsw.msg.HandleBatchMessagesResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.base_ = baseBuilder_ == null
            ? base_
            : baseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.successCount_ = successCount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.failCount_ = failCount_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bdsw.msg.HandleBatchMessagesResponse) {
        return mergeFrom((com.bdsw.msg.HandleBatchMessagesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bdsw.msg.HandleBatchMessagesResponse other) {
      if (other == com.bdsw.msg.HandleBatchMessagesResponse.getDefaultInstance()) return this;
      if (other.hasBase()) {
        mergeBase(other.getBase());
      }
      if (responsesBuilder_ == null) {
        if (!other.responses_.isEmpty()) {
          if (responses_.isEmpty()) {
            responses_ = other.responses_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureResponsesIsMutable();
            responses_.addAll(other.responses_);
          }
          onChanged();
        }
      } else {
        if (!other.responses_.isEmpty()) {
          if (responsesBuilder_.isEmpty()) {
            responsesBuilder_.dispose();
            responsesBuilder_ = null;
            responses_ = other.responses_;
            bitField0_ = (bitField0_ & ~0x00000002);
            responsesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetResponsesFieldBuilder() : null;
          } else {
            responsesBuilder_.addAllMessages(other.responses_);
          }
        }
      }
      if (other.getSuccessCount() != 0) {
        setSuccessCount(other.getSuccessCount());
      }
      if (other.getFailCount() != 0) {
        setFailCount(other.getFailCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBaseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.bdsw.common.ServerMessage m =
                  input.readMessage(
                      com.bdsw.common.ServerMessage.parser(),
                      extensionRegistry);
              if (responsesBuilder_ == null) {
                ensureResponsesIsMutable();
                responses_.add(m);
              } else {
                responsesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 24: {
              successCount_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              failCount_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.bdsw.common.BaseResponse base_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bdsw.common.BaseResponse, com.bdsw.common.BaseResponse.Builder, com.bdsw.common.BaseResponseOrBuilder> baseBuilder_;
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     * @return Whether the base field is set.
     */
    public boolean hasBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     * @return The base.
     */
    public com.bdsw.common.BaseResponse getBase() {
      if (baseBuilder_ == null) {
        return base_ == null ? com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
      } else {
        return baseBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder setBase(com.bdsw.common.BaseResponse value) {
      if (baseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        base_ = value;
      } else {
        baseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder setBase(
        com.bdsw.common.BaseResponse.Builder builderForValue) {
      if (baseBuilder_ == null) {
        base_ = builderForValue.build();
      } else {
        baseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder mergeBase(com.bdsw.common.BaseResponse value) {
      if (baseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          base_ != null &&
          base_ != com.bdsw.common.BaseResponse.getDefaultInstance()) {
          getBaseBuilder().mergeFrom(value);
        } else {
          base_ = value;
        }
      } else {
        baseBuilder_.mergeFrom(value);
      }
      if (base_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder clearBase() {
      bitField0_ = (bitField0_ & ~0x00000001);
      base_ = null;
      if (baseBuilder_ != null) {
        baseBuilder_.dispose();
        baseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public com.bdsw.common.BaseResponse.Builder getBaseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBaseFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder() {
      if (baseBuilder_ != null) {
        return baseBuilder_.getMessageOrBuilder();
      } else {
        return base_ == null ?
            com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
      }
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bdsw.common.BaseResponse, com.bdsw.common.BaseResponse.Builder, com.bdsw.common.BaseResponseOrBuilder> 
        internalGetBaseFieldBuilder() {
      if (baseBuilder_ == null) {
        baseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bdsw.common.BaseResponse, com.bdsw.common.BaseResponse.Builder, com.bdsw.common.BaseResponseOrBuilder>(
                getBase(),
                getParentForChildren(),
                isClean());
        base_ = null;
      }
      return baseBuilder_;
    }

    private java.util.List<com.bdsw.common.ServerMessage> responses_ =
      java.util.Collections.emptyList();
    private void ensureResponsesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        responses_ = new java.util.ArrayList<com.bdsw.common.ServerMessage>(responses_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bdsw.common.ServerMessage, com.bdsw.common.ServerMessage.Builder, com.bdsw.common.ServerMessageOrBuilder> responsesBuilder_;

    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public java.util.List<com.bdsw.common.ServerMessage> getResponsesList() {
      if (responsesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(responses_);
      } else {
        return responsesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public int getResponsesCount() {
      if (responsesBuilder_ == null) {
        return responses_.size();
      } else {
        return responsesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public com.bdsw.common.ServerMessage getResponses(int index) {
      if (responsesBuilder_ == null) {
        return responses_.get(index);
      } else {
        return responsesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public Builder setResponses(
        int index, com.bdsw.common.ServerMessage value) {
      if (responsesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponsesIsMutable();
        responses_.set(index, value);
        onChanged();
      } else {
        responsesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public Builder setResponses(
        int index, com.bdsw.common.ServerMessage.Builder builderForValue) {
      if (responsesBuilder_ == null) {
        ensureResponsesIsMutable();
        responses_.set(index, builderForValue.build());
        onChanged();
      } else {
        responsesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public Builder addResponses(com.bdsw.common.ServerMessage value) {
      if (responsesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponsesIsMutable();
        responses_.add(value);
        onChanged();
      } else {
        responsesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public Builder addResponses(
        int index, com.bdsw.common.ServerMessage value) {
      if (responsesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponsesIsMutable();
        responses_.add(index, value);
        onChanged();
      } else {
        responsesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public Builder addResponses(
        com.bdsw.common.ServerMessage.Builder builderForValue) {
      if (responsesBuilder_ == null) {
        ensureResponsesIsMutable();
        responses_.add(builderForValue.build());
        onChanged();
      } else {
        responsesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public Builder addResponses(
        int index, com.bdsw.common.ServerMessage.Builder builderForValue) {
      if (responsesBuilder_ == null) {
        ensureResponsesIsMutable();
        responses_.add(index, builderForValue.build());
        onChanged();
      } else {
        responsesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public Builder addAllResponses(
        java.lang.Iterable<? extends com.bdsw.common.ServerMessage> values) {
      if (responsesBuilder_ == null) {
        ensureResponsesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, responses_);
        onChanged();
      } else {
        responsesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public Builder clearResponses() {
      if (responsesBuilder_ == null) {
        responses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        responsesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public Builder removeResponses(int index) {
      if (responsesBuilder_ == null) {
        ensureResponsesIsMutable();
        responses_.remove(index);
        onChanged();
      } else {
        responsesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public com.bdsw.common.ServerMessage.Builder getResponsesBuilder(
        int index) {
      return internalGetResponsesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public com.bdsw.common.ServerMessageOrBuilder getResponsesOrBuilder(
        int index) {
      if (responsesBuilder_ == null) {
        return responses_.get(index);  } else {
        return responsesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public java.util.List<? extends com.bdsw.common.ServerMessageOrBuilder> 
         getResponsesOrBuilderList() {
      if (responsesBuilder_ != null) {
        return responsesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(responses_);
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public com.bdsw.common.ServerMessage.Builder addResponsesBuilder() {
      return internalGetResponsesFieldBuilder().addBuilder(
          com.bdsw.common.ServerMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public com.bdsw.common.ServerMessage.Builder addResponsesBuilder(
        int index) {
      return internalGetResponsesFieldBuilder().addBuilder(
          index, com.bdsw.common.ServerMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
     */
    public java.util.List<com.bdsw.common.ServerMessage.Builder> 
         getResponsesBuilderList() {
      return internalGetResponsesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bdsw.common.ServerMessage, com.bdsw.common.ServerMessage.Builder, com.bdsw.common.ServerMessageOrBuilder> 
        internalGetResponsesFieldBuilder() {
      if (responsesBuilder_ == null) {
        responsesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bdsw.common.ServerMessage, com.bdsw.common.ServerMessage.Builder, com.bdsw.common.ServerMessageOrBuilder>(
                responses_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        responses_ = null;
      }
      return responsesBuilder_;
    }

    private int successCount_ ;
    /**
     * <code>int32 success_count = 3;</code>
     * @return The successCount.
     */
    @java.lang.Override
    public int getSuccessCount() {
      return successCount_;
    }
    /**
     * <code>int32 success_count = 3;</code>
     * @param value The successCount to set.
     * @return This builder for chaining.
     */
    public Builder setSuccessCount(int value) {

      successCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 success_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccessCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      successCount_ = 0;
      onChanged();
      return this;
    }

    private int failCount_ ;
    /**
     * <code>int32 fail_count = 4;</code>
     * @return The failCount.
     */
    @java.lang.Override
    public int getFailCount() {
      return failCount_;
    }
    /**
     * <code>int32 fail_count = 4;</code>
     * @param value The failCount to set.
     * @return This builder for chaining.
     */
    public Builder setFailCount(int value) {

      failCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 fail_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFailCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      failCount_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bdsw.msg.HandleBatchMessagesResponse)
  }

  // @@protoc_insertion_point(class_scope:com.bdsw.msg.HandleBatchMessagesResponse)
  private static final com.bdsw.msg.HandleBatchMessagesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bdsw.msg.HandleBatchMessagesResponse();
  }

  public static com.bdsw.msg.HandleBatchMessagesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HandleBatchMessagesResponse>
      PARSER = new com.google.protobuf.AbstractParser<HandleBatchMessagesResponse>() {
    @java.lang.Override
    public HandleBatchMessagesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HandleBatchMessagesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HandleBatchMessagesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bdsw.msg.HandleBatchMessagesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

