// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

@com.google.protobuf.Generated
public interface HandleBatchMessagesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.msg.HandleBatchMessagesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return The base.
   */
  com.bdsw.common.BaseResponse getBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   */
  com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder();

  /**
   * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
   */
  java.util.List<com.bdsw.common.ServerMessage> 
      getResponsesList();
  /**
   * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
   */
  com.bdsw.common.ServerMessage getResponses(int index);
  /**
   * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
   */
  int getResponsesCount();
  /**
   * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
   */
  java.util.List<? extends com.bdsw.common.ServerMessageOrBuilder> 
      getResponsesOrBuilderList();
  /**
   * <code>repeated .com.bdsw.common.ServerMessage responses = 2;</code>
   */
  com.bdsw.common.ServerMessageOrBuilder getResponsesOrBuilder(
      int index);

  /**
   * <code>int32 success_count = 3;</code>
   * @return The successCount.
   */
  int getSuccessCount();

  /**
   * <code>int32 fail_count = 4;</code>
   * @return The failCount.
   */
  int getFailCount();
}
