// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

@com.google.protobuf.Generated
public interface HandleBatchMessagesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.msg.HandleBatchMessagesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
   */
  java.util.List<com.bdsw.common.ClientMessage> 
      getMessagesList();
  /**
   * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
   */
  com.bdsw.common.ClientMessage getMessages(int index);
  /**
   * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
   */
  java.util.List<? extends com.bdsw.common.ClientMessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
   */
  com.bdsw.common.ClientMessageOrBuilder getMessagesOrBuilder(
      int index);
}
