// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

/**
 * <pre>
 * 处理批量消息请求
 * </pre>
 *
 * Protobuf type {@code com.bdsw.msg.HandleBatchMessagesRequest}
 */
@com.google.protobuf.Generated
public final class HandleBatchMessagesRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bdsw.msg.HandleBatchMessagesRequest)
    HandleBatchMessagesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      HandleBatchMessagesRequest.class.getName());
  }
  // Use HandleBatchMessagesRequest.newBuilder() to construct.
  private HandleBatchMessagesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HandleBatchMessagesRequest() {
    messages_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_HandleBatchMessagesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_HandleBatchMessagesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bdsw.msg.HandleBatchMessagesRequest.class, com.bdsw.msg.HandleBatchMessagesRequest.Builder.class);
  }

  public static final int MESSAGES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.bdsw.common.ClientMessage> messages_;
  /**
   * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.bdsw.common.ClientMessage> getMessagesList() {
    return messages_;
  }
  /**
   * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.bdsw.common.ClientMessageOrBuilder> 
      getMessagesOrBuilderList() {
    return messages_;
  }
  /**
   * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
   */
  @java.lang.Override
  public int getMessagesCount() {
    return messages_.size();
  }
  /**
   * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
   */
  @java.lang.Override
  public com.bdsw.common.ClientMessage getMessages(int index) {
    return messages_.get(index);
  }
  /**
   * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
   */
  @java.lang.Override
  public com.bdsw.common.ClientMessageOrBuilder getMessagesOrBuilder(
      int index) {
    return messages_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < messages_.size(); i++) {
      output.writeMessage(1, messages_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < messages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, messages_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bdsw.msg.HandleBatchMessagesRequest)) {
      return super.equals(obj);
    }
    com.bdsw.msg.HandleBatchMessagesRequest other = (com.bdsw.msg.HandleBatchMessagesRequest) obj;

    if (!getMessagesList()
        .equals(other.getMessagesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMessagesCount() > 0) {
      hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
      hash = (53 * hash) + getMessagesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bdsw.msg.HandleBatchMessagesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.HandleBatchMessagesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.HandleBatchMessagesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.HandleBatchMessagesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.HandleBatchMessagesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.HandleBatchMessagesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.HandleBatchMessagesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.msg.HandleBatchMessagesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bdsw.msg.HandleBatchMessagesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bdsw.msg.HandleBatchMessagesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bdsw.msg.HandleBatchMessagesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.msg.HandleBatchMessagesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bdsw.msg.HandleBatchMessagesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 处理批量消息请求
   * </pre>
   *
   * Protobuf type {@code com.bdsw.msg.HandleBatchMessagesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bdsw.msg.HandleBatchMessagesRequest)
      com.bdsw.msg.HandleBatchMessagesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_HandleBatchMessagesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_HandleBatchMessagesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bdsw.msg.HandleBatchMessagesRequest.class, com.bdsw.msg.HandleBatchMessagesRequest.Builder.class);
    }

    // Construct using com.bdsw.msg.HandleBatchMessagesRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
      } else {
        messages_ = null;
        messagesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_HandleBatchMessagesRequest_descriptor;
    }

    @java.lang.Override
    public com.bdsw.msg.HandleBatchMessagesRequest getDefaultInstanceForType() {
      return com.bdsw.msg.HandleBatchMessagesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.bdsw.msg.HandleBatchMessagesRequest build() {
      com.bdsw.msg.HandleBatchMessagesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bdsw.msg.HandleBatchMessagesRequest buildPartial() {
      com.bdsw.msg.HandleBatchMessagesRequest result = new com.bdsw.msg.HandleBatchMessagesRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.bdsw.msg.HandleBatchMessagesRequest result) {
      if (messagesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.messages_ = messages_;
      } else {
        result.messages_ = messagesBuilder_.build();
      }
    }

    private void buildPartial0(com.bdsw.msg.HandleBatchMessagesRequest result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bdsw.msg.HandleBatchMessagesRequest) {
        return mergeFrom((com.bdsw.msg.HandleBatchMessagesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bdsw.msg.HandleBatchMessagesRequest other) {
      if (other == com.bdsw.msg.HandleBatchMessagesRequest.getDefaultInstance()) return this;
      if (messagesBuilder_ == null) {
        if (!other.messages_.isEmpty()) {
          if (messages_.isEmpty()) {
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessagesIsMutable();
            messages_.addAll(other.messages_);
          }
          onChanged();
        }
      } else {
        if (!other.messages_.isEmpty()) {
          if (messagesBuilder_.isEmpty()) {
            messagesBuilder_.dispose();
            messagesBuilder_ = null;
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000001);
            messagesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetMessagesFieldBuilder() : null;
          } else {
            messagesBuilder_.addAllMessages(other.messages_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.bdsw.common.ClientMessage m =
                  input.readMessage(
                      com.bdsw.common.ClientMessage.parser(),
                      extensionRegistry);
              if (messagesBuilder_ == null) {
                ensureMessagesIsMutable();
                messages_.add(m);
              } else {
                messagesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.bdsw.common.ClientMessage> messages_ =
      java.util.Collections.emptyList();
    private void ensureMessagesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        messages_ = new java.util.ArrayList<com.bdsw.common.ClientMessage>(messages_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bdsw.common.ClientMessage, com.bdsw.common.ClientMessage.Builder, com.bdsw.common.ClientMessageOrBuilder> messagesBuilder_;

    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public java.util.List<com.bdsw.common.ClientMessage> getMessagesList() {
      if (messagesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(messages_);
      } else {
        return messagesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public int getMessagesCount() {
      if (messagesBuilder_ == null) {
        return messages_.size();
      } else {
        return messagesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public com.bdsw.common.ClientMessage getMessages(int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);
      } else {
        return messagesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public Builder setMessages(
        int index, com.bdsw.common.ClientMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.set(index, value);
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public Builder setMessages(
        int index, com.bdsw.common.ClientMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.set(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public Builder addMessages(com.bdsw.common.ClientMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public Builder addMessages(
        int index, com.bdsw.common.ClientMessage value) {
      if (messagesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMessagesIsMutable();
        messages_.add(index, value);
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public Builder addMessages(
        com.bdsw.common.ClientMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public Builder addMessages(
        int index, com.bdsw.common.ClientMessage.Builder builderForValue) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.add(index, builderForValue.build());
        onChanged();
      } else {
        messagesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public Builder addAllMessages(
        java.lang.Iterable<? extends com.bdsw.common.ClientMessage> values) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messages_);
        onChanged();
      } else {
        messagesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public Builder clearMessages() {
      if (messagesBuilder_ == null) {
        messages_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        messagesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public Builder removeMessages(int index) {
      if (messagesBuilder_ == null) {
        ensureMessagesIsMutable();
        messages_.remove(index);
        onChanged();
      } else {
        messagesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public com.bdsw.common.ClientMessage.Builder getMessagesBuilder(
        int index) {
      return internalGetMessagesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public com.bdsw.common.ClientMessageOrBuilder getMessagesOrBuilder(
        int index) {
      if (messagesBuilder_ == null) {
        return messages_.get(index);  } else {
        return messagesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public java.util.List<? extends com.bdsw.common.ClientMessageOrBuilder> 
         getMessagesOrBuilderList() {
      if (messagesBuilder_ != null) {
        return messagesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(messages_);
      }
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public com.bdsw.common.ClientMessage.Builder addMessagesBuilder() {
      return internalGetMessagesFieldBuilder().addBuilder(
          com.bdsw.common.ClientMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public com.bdsw.common.ClientMessage.Builder addMessagesBuilder(
        int index) {
      return internalGetMessagesFieldBuilder().addBuilder(
          index, com.bdsw.common.ClientMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bdsw.common.ClientMessage messages = 1;</code>
     */
    public java.util.List<com.bdsw.common.ClientMessage.Builder> 
         getMessagesBuilderList() {
      return internalGetMessagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bdsw.common.ClientMessage, com.bdsw.common.ClientMessage.Builder, com.bdsw.common.ClientMessageOrBuilder> 
        internalGetMessagesFieldBuilder() {
      if (messagesBuilder_ == null) {
        messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bdsw.common.ClientMessage, com.bdsw.common.ClientMessage.Builder, com.bdsw.common.ClientMessageOrBuilder>(
                messages_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        messages_ = null;
      }
      return messagesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.bdsw.msg.HandleBatchMessagesRequest)
  }

  // @@protoc_insertion_point(class_scope:com.bdsw.msg.HandleBatchMessagesRequest)
  private static final com.bdsw.msg.HandleBatchMessagesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bdsw.msg.HandleBatchMessagesRequest();
  }

  public static com.bdsw.msg.HandleBatchMessagesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HandleBatchMessagesRequest>
      PARSER = new com.google.protobuf.AbstractParser<HandleBatchMessagesRequest>() {
    @java.lang.Override
    public HandleBatchMessagesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HandleBatchMessagesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HandleBatchMessagesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bdsw.msg.HandleBatchMessagesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

