// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

@com.google.protobuf.Generated
public interface MessageReadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.msg.MessageReadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string session_id = 2;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 2;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * 为空表示已读该会话所有消息
   * </pre>
   *
   * <code>string message_id = 3;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <pre>
   * 为空表示已读该会话所有消息
   * </pre>
   *
   * <code>string message_id = 3;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>int64 read_time = 4;</code>
   * @return The readTime.
   */
  long getReadTime();
}
