// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

@com.google.protobuf.Generated
public final class MsgProto extends com.google.protobuf.GeneratedFile {
  private MsgProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      MsgProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_msg_HandleBatchMessagesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_msg_HandleBatchMessagesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_msg_HandleBatchMessagesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_msg_HandleBatchMessagesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_msg_SessionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_msg_SessionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_msg_GetUserSessionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_msg_GetUserSessionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_msg_GetUserSessionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_msg_GetUserSessionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_msg_GetChatHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_msg_GetChatHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_msg_GetChatHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_msg_GetChatHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_msg_MessageReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_msg_MessageReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_msg_RecallMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_msg_RecallMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_msg_KickUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_msg_KickUserRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\014com.bdsw.msg\032\014common.proto\"" +
      "N\n\032HandleBatchMessagesRequest\0220\n\010message" +
      "s\030\001 \003(\0132\036.com.bdsw.common.ClientMessage\"" +
      "\250\001\n\033HandleBatchMessagesResponse\022+\n\004base\030" +
      "\001 \001(\0132\035.com.bdsw.common.BaseResponse\0221\n\t" +
      "responses\030\002 \003(\0132\036.com.bdsw.common.Server" +
      "Message\022\025\n\rsuccess_count\030\003 \001(\005\022\022\n\nfail_c" +
      "ount\030\004 \001(\005\"\257\001\n\013SessionInfo\022\022\n\nsession_id" +
      "\030\001 \001(\t\022\024\n\014session_type\030\002 \001(\t\022\021\n\ttarget_i" +
      "d\030\003 \001(\t\022\024\n\014last_message\030\004 \001(\t\022\031\n\021last_me" +
      "ssage_time\030\005 \001(\003\022\024\n\014unread_count\030\006 \001(\005\022\016" +
      "\n\006is_top\030\007 \001(\010\022\014\n\004mute\030\010 \001(\010\"U\n\026GetUserS" +
      "essionsRequest\022\017\n\007user_id\030\001 \001(\t\022*\n\004page\030" +
      "\002 \001(\0132\034.com.bdsw.common.PageRequest\"\240\001\n\027" +
      "GetUserSessionsResponse\022+\n\004base\030\001 \001(\0132\035." +
      "com.bdsw.common.BaseResponse\022+\n\010sessions" +
      "\030\002 \003(\0132\031.com.bdsw.msg.SessionInfo\022+\n\004pag" +
      "e\030\003 \001(\0132\035.com.bdsw.common.PageResponse\"\216" +
      "\001\n\025GetChatHistoryRequest\022\022\n\nsession_id\030\001" +
      " \001(\t\022\017\n\007user_id\030\002 \001(\t\022\022\n\nstart_time\030\003 \001(" +
      "\003\022\020\n\010end_time\030\004 \001(\003\022*\n\004page\030\005 \001(\0132\034.com." +
      "bdsw.common.PageRequest\"\244\001\n\026GetChatHisto" +
      "ryResponse\022+\n\004base\030\001 \001(\0132\035.com.bdsw.comm" +
      "on.BaseResponse\0220\n\010messages\030\002 \003(\0132\036.com." +
      "bdsw.common.ServerMessage\022+\n\004page\030\003 \001(\0132" +
      "\035.com.bdsw.common.PageResponse\"`\n\022Messag" +
      "eReadRequest\022\017\n\007user_id\030\001 \001(\t\022\022\n\nsession" +
      "_id\030\002 \001(\t\022\022\n\nmessage_id\030\003 \001(\t\022\021\n\tread_ti" +
      "me\030\004 \001(\003\"K\n\024RecallMessageRequest\022\017\n\007user" +
      "_id\030\001 \001(\t\022\022\n\nmessage_id\030\002 \001(\t\022\016\n\006reason\030" +
      "\003 \001(\t\"W\n\017KickUserRequest\022\017\n\007user_id\030\001 \001(" +
      "\t\022\021\n\tdevice_id\030\002 \001(\t\022\016\n\006reason\030\003 \001(\t\022\020\n\010" +
      "operator\030\004 \001(\t2\214\005\n\nMsgService\022W\n\023HandleC" +
      "lientMessage\022\036.com.bdsw.common.ClientMes" +
      "sage\032\036.com.bdsw.common.ServerMessage\"\000\022l" +
      "\n\023HandleBatchMessages\022(.com.bdsw.msg.Han" +
      "dleBatchMessagesRequest\032).com.bdsw.msg.H" +
      "andleBatchMessagesResponse\"\000\022`\n\017GetUserS" +
      "essions\022$.com.bdsw.msg.GetUserSessionsRe" +
      "quest\032%.com.bdsw.msg.GetUserSessionsResp" +
      "onse\"\000\022]\n\016GetChatHistory\022#.com.bdsw.msg." +
      "GetChatHistoryRequest\032$.com.bdsw.msg.Get" +
      "ChatHistoryResponse\"\000\022T\n\017MarkMessageRead" +
      "\022 .com.bdsw.msg.MessageReadRequest\032\035.com" +
      ".bdsw.common.BaseResponse\"\000\022T\n\rRecallMes" +
      "sage\022\".com.bdsw.msg.RecallMessageRequest" +
      "\032\035.com.bdsw.common.BaseResponse\"\000\022J\n\010Kic" +
      "kUser\022\035.com.bdsw.msg.KickUserRequest\032\035.c" +
      "om.bdsw.common.BaseResponse\"\000BB\n\014com.bds" +
      "w.msgB\010MsgProtoP\001Z&github.com/bdsw/bdsw-" +
      "im-ws/api/msg;msgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bdsw.common.CommonProto.getDescriptor(),
        });
    internal_static_com_bdsw_msg_HandleBatchMessagesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bdsw_msg_HandleBatchMessagesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_msg_HandleBatchMessagesRequest_descriptor,
        new java.lang.String[] { "Messages", });
    internal_static_com_bdsw_msg_HandleBatchMessagesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bdsw_msg_HandleBatchMessagesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_msg_HandleBatchMessagesResponse_descriptor,
        new java.lang.String[] { "Base", "Responses", "SuccessCount", "FailCount", });
    internal_static_com_bdsw_msg_SessionInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_bdsw_msg_SessionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_msg_SessionInfo_descriptor,
        new java.lang.String[] { "SessionId", "SessionType", "TargetId", "LastMessage", "LastMessageTime", "UnreadCount", "IsTop", "Mute", });
    internal_static_com_bdsw_msg_GetUserSessionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_bdsw_msg_GetUserSessionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_msg_GetUserSessionsRequest_descriptor,
        new java.lang.String[] { "UserId", "Page", });
    internal_static_com_bdsw_msg_GetUserSessionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_bdsw_msg_GetUserSessionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_msg_GetUserSessionsResponse_descriptor,
        new java.lang.String[] { "Base", "Sessions", "Page", });
    internal_static_com_bdsw_msg_GetChatHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_bdsw_msg_GetChatHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_msg_GetChatHistoryRequest_descriptor,
        new java.lang.String[] { "SessionId", "UserId", "StartTime", "EndTime", "Page", });
    internal_static_com_bdsw_msg_GetChatHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_bdsw_msg_GetChatHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_msg_GetChatHistoryResponse_descriptor,
        new java.lang.String[] { "Base", "Messages", "Page", });
    internal_static_com_bdsw_msg_MessageReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_bdsw_msg_MessageReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_msg_MessageReadRequest_descriptor,
        new java.lang.String[] { "UserId", "SessionId", "MessageId", "ReadTime", });
    internal_static_com_bdsw_msg_RecallMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_bdsw_msg_RecallMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_msg_RecallMessageRequest_descriptor,
        new java.lang.String[] { "UserId", "MessageId", "Reason", });
    internal_static_com_bdsw_msg_KickUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_bdsw_msg_KickUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_msg_KickUserRequest_descriptor,
        new java.lang.String[] { "UserId", "DeviceId", "Reason", "Operator", });
    descriptor.resolveAllFeaturesImmutable();
    com.bdsw.common.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
