// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

@com.google.protobuf.Generated
public interface SessionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.msg.SessionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * single, group, system
   * </pre>
   *
   * <code>string session_type = 2;</code>
   * @return The sessionType.
   */
  java.lang.String getSessionType();
  /**
   * <pre>
   * single, group, system
   * </pre>
   *
   * <code>string session_type = 2;</code>
   * @return The bytes for sessionType.
   */
  com.google.protobuf.ByteString
      getSessionTypeBytes();

  /**
   * <code>string target_id = 3;</code>
   * @return The targetId.
   */
  java.lang.String getTargetId();
  /**
   * <code>string target_id = 3;</code>
   * @return The bytes for targetId.
   */
  com.google.protobuf.ByteString
      getTargetIdBytes();

  /**
   * <code>string last_message = 4;</code>
   * @return The lastMessage.
   */
  java.lang.String getLastMessage();
  /**
   * <code>string last_message = 4;</code>
   * @return The bytes for lastMessage.
   */
  com.google.protobuf.ByteString
      getLastMessageBytes();

  /**
   * <code>int64 last_message_time = 5;</code>
   * @return The lastMessageTime.
   */
  long getLastMessageTime();

  /**
   * <code>int32 unread_count = 6;</code>
   * @return The unreadCount.
   */
  int getUnreadCount();

  /**
   * <code>bool is_top = 7;</code>
   * @return The isTop.
   */
  boolean getIsTop();

  /**
   * <code>bool mute = 8;</code>
   * @return The mute.
   */
  boolean getMute();
}
