// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.msg;

/**
 * <pre>
 * 会话信息
 * </pre>
 *
 * Protobuf type {@code com.bdsw.msg.SessionInfo}
 */
@com.google.protobuf.Generated
public final class SessionInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bdsw.msg.SessionInfo)
    SessionInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      SessionInfo.class.getName());
  }
  // Use SessionInfo.newBuilder() to construct.
  private SessionInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SessionInfo() {
    sessionId_ = "";
    sessionType_ = "";
    targetId_ = "";
    lastMessage_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_SessionInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_SessionInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bdsw.msg.SessionInfo.class, com.bdsw.msg.SessionInfo.Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionType_ = "";
  /**
   * <pre>
   * single, group, system
   * </pre>
   *
   * <code>string session_type = 2;</code>
   * @return The sessionType.
   */
  @java.lang.Override
  public java.lang.String getSessionType() {
    java.lang.Object ref = sessionType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * single, group, system
   * </pre>
   *
   * <code>string session_type = 2;</code>
   * @return The bytes for sessionType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionTypeBytes() {
    java.lang.Object ref = sessionType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object targetId_ = "";
  /**
   * <code>string target_id = 3;</code>
   * @return The targetId.
   */
  @java.lang.Override
  public java.lang.String getTargetId() {
    java.lang.Object ref = targetId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetId_ = s;
      return s;
    }
  }
  /**
   * <code>string target_id = 3;</code>
   * @return The bytes for targetId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetIdBytes() {
    java.lang.Object ref = targetId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_MESSAGE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastMessage_ = "";
  /**
   * <code>string last_message = 4;</code>
   * @return The lastMessage.
   */
  @java.lang.Override
  public java.lang.String getLastMessage() {
    java.lang.Object ref = lastMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string last_message = 4;</code>
   * @return The bytes for lastMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastMessageBytes() {
    java.lang.Object ref = lastMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_MESSAGE_TIME_FIELD_NUMBER = 5;
  private long lastMessageTime_ = 0L;
  /**
   * <code>int64 last_message_time = 5;</code>
   * @return The lastMessageTime.
   */
  @java.lang.Override
  public long getLastMessageTime() {
    return lastMessageTime_;
  }

  public static final int UNREAD_COUNT_FIELD_NUMBER = 6;
  private int unreadCount_ = 0;
  /**
   * <code>int32 unread_count = 6;</code>
   * @return The unreadCount.
   */
  @java.lang.Override
  public int getUnreadCount() {
    return unreadCount_;
  }

  public static final int IS_TOP_FIELD_NUMBER = 7;
  private boolean isTop_ = false;
  /**
   * <code>bool is_top = 7;</code>
   * @return The isTop.
   */
  @java.lang.Override
  public boolean getIsTop() {
    return isTop_;
  }

  public static final int MUTE_FIELD_NUMBER = 8;
  private boolean mute_ = false;
  /**
   * <code>bool mute = 8;</code>
   * @return The mute.
   */
  @java.lang.Override
  public boolean getMute() {
    return mute_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, sessionType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, targetId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastMessage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, lastMessage_);
    }
    if (lastMessageTime_ != 0L) {
      output.writeInt64(5, lastMessageTime_);
    }
    if (unreadCount_ != 0) {
      output.writeInt32(6, unreadCount_);
    }
    if (isTop_ != false) {
      output.writeBool(7, isTop_);
    }
    if (mute_ != false) {
      output.writeBool(8, mute_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, sessionType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(targetId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, targetId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastMessage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, lastMessage_);
    }
    if (lastMessageTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, lastMessageTime_);
    }
    if (unreadCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, unreadCount_);
    }
    if (isTop_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, isTop_);
    }
    if (mute_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, mute_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bdsw.msg.SessionInfo)) {
      return super.equals(obj);
    }
    com.bdsw.msg.SessionInfo other = (com.bdsw.msg.SessionInfo) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (!getSessionType()
        .equals(other.getSessionType())) return false;
    if (!getTargetId()
        .equals(other.getTargetId())) return false;
    if (!getLastMessage()
        .equals(other.getLastMessage())) return false;
    if (getLastMessageTime()
        != other.getLastMessageTime()) return false;
    if (getUnreadCount()
        != other.getUnreadCount()) return false;
    if (getIsTop()
        != other.getIsTop()) return false;
    if (getMute()
        != other.getMute()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    hash = (37 * hash) + SESSION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSessionType().hashCode();
    hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTargetId().hashCode();
    hash = (37 * hash) + LAST_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getLastMessage().hashCode();
    hash = (37 * hash) + LAST_MESSAGE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastMessageTime());
    hash = (37 * hash) + UNREAD_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getUnreadCount();
    hash = (37 * hash) + IS_TOP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsTop());
    hash = (37 * hash) + MUTE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMute());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bdsw.msg.SessionInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.SessionInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.SessionInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.SessionInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.SessionInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.msg.SessionInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.msg.SessionInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.msg.SessionInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bdsw.msg.SessionInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bdsw.msg.SessionInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bdsw.msg.SessionInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.msg.SessionInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bdsw.msg.SessionInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 会话信息
   * </pre>
   *
   * Protobuf type {@code com.bdsw.msg.SessionInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bdsw.msg.SessionInfo)
      com.bdsw.msg.SessionInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_SessionInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_SessionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bdsw.msg.SessionInfo.class, com.bdsw.msg.SessionInfo.Builder.class);
    }

    // Construct using com.bdsw.msg.SessionInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      sessionType_ = "";
      targetId_ = "";
      lastMessage_ = "";
      lastMessageTime_ = 0L;
      unreadCount_ = 0;
      isTop_ = false;
      mute_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bdsw.msg.MsgProto.internal_static_com_bdsw_msg_SessionInfo_descriptor;
    }

    @java.lang.Override
    public com.bdsw.msg.SessionInfo getDefaultInstanceForType() {
      return com.bdsw.msg.SessionInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.bdsw.msg.SessionInfo build() {
      com.bdsw.msg.SessionInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bdsw.msg.SessionInfo buildPartial() {
      com.bdsw.msg.SessionInfo result = new com.bdsw.msg.SessionInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bdsw.msg.SessionInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sessionType_ = sessionType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.targetId_ = targetId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lastMessage_ = lastMessage_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.lastMessageTime_ = lastMessageTime_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.unreadCount_ = unreadCount_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.isTop_ = isTop_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.mute_ = mute_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bdsw.msg.SessionInfo) {
        return mergeFrom((com.bdsw.msg.SessionInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bdsw.msg.SessionInfo other) {
      if (other == com.bdsw.msg.SessionInfo.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSessionType().isEmpty()) {
        sessionType_ = other.sessionType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTargetId().isEmpty()) {
        targetId_ = other.targetId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getLastMessage().isEmpty()) {
        lastMessage_ = other.lastMessage_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getLastMessageTime() != 0L) {
        setLastMessageTime(other.getLastMessageTime());
      }
      if (other.getUnreadCount() != 0) {
        setUnreadCount(other.getUnreadCount());
      }
      if (other.getIsTop() != false) {
        setIsTop(other.getIsTop());
      }
      if (other.getMute() != false) {
        setMute(other.getMute());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              sessionType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              targetId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              lastMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              lastMessageTime_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              unreadCount_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              isTop_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              mute_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 1;</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 1;</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 1;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1;</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object sessionType_ = "";
    /**
     * <pre>
     * single, group, system
     * </pre>
     *
     * <code>string session_type = 2;</code>
     * @return The sessionType.
     */
    public java.lang.String getSessionType() {
      java.lang.Object ref = sessionType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * single, group, system
     * </pre>
     *
     * <code>string session_type = 2;</code>
     * @return The bytes for sessionType.
     */
    public com.google.protobuf.ByteString
        getSessionTypeBytes() {
      java.lang.Object ref = sessionType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * single, group, system
     * </pre>
     *
     * <code>string session_type = 2;</code>
     * @param value The sessionType to set.
     * @return This builder for chaining.
     */
    public Builder setSessionType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * single, group, system
     * </pre>
     *
     * <code>string session_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionType() {
      sessionType_ = getDefaultInstance().getSessionType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * single, group, system
     * </pre>
     *
     * <code>string session_type = 2;</code>
     * @param value The bytes for sessionType to set.
     * @return This builder for chaining.
     */
    public Builder setSessionTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object targetId_ = "";
    /**
     * <code>string target_id = 3;</code>
     * @return The targetId.
     */
    public java.lang.String getTargetId() {
      java.lang.Object ref = targetId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string target_id = 3;</code>
     * @return The bytes for targetId.
     */
    public com.google.protobuf.ByteString
        getTargetIdBytes() {
      java.lang.Object ref = targetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string target_id = 3;</code>
     * @param value The targetId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      targetId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string target_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetId() {
      targetId_ = getDefaultInstance().getTargetId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string target_id = 3;</code>
     * @param value The bytes for targetId to set.
     * @return This builder for chaining.
     */
    public Builder setTargetIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      targetId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object lastMessage_ = "";
    /**
     * <code>string last_message = 4;</code>
     * @return The lastMessage.
     */
    public java.lang.String getLastMessage() {
      java.lang.Object ref = lastMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string last_message = 4;</code>
     * @return The bytes for lastMessage.
     */
    public com.google.protobuf.ByteString
        getLastMessageBytes() {
      java.lang.Object ref = lastMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string last_message = 4;</code>
     * @param value The lastMessage to set.
     * @return This builder for chaining.
     */
    public Builder setLastMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastMessage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string last_message = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastMessage() {
      lastMessage_ = getDefaultInstance().getLastMessage();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string last_message = 4;</code>
     * @param value The bytes for lastMessage to set.
     * @return This builder for chaining.
     */
    public Builder setLastMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastMessage_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long lastMessageTime_ ;
    /**
     * <code>int64 last_message_time = 5;</code>
     * @return The lastMessageTime.
     */
    @java.lang.Override
    public long getLastMessageTime() {
      return lastMessageTime_;
    }
    /**
     * <code>int64 last_message_time = 5;</code>
     * @param value The lastMessageTime to set.
     * @return This builder for chaining.
     */
    public Builder setLastMessageTime(long value) {

      lastMessageTime_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_message_time = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastMessageTime() {
      bitField0_ = (bitField0_ & ~0x00000010);
      lastMessageTime_ = 0L;
      onChanged();
      return this;
    }

    private int unreadCount_ ;
    /**
     * <code>int32 unread_count = 6;</code>
     * @return The unreadCount.
     */
    @java.lang.Override
    public int getUnreadCount() {
      return unreadCount_;
    }
    /**
     * <code>int32 unread_count = 6;</code>
     * @param value The unreadCount to set.
     * @return This builder for chaining.
     */
    public Builder setUnreadCount(int value) {

      unreadCount_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 unread_count = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnreadCount() {
      bitField0_ = (bitField0_ & ~0x00000020);
      unreadCount_ = 0;
      onChanged();
      return this;
    }

    private boolean isTop_ ;
    /**
     * <code>bool is_top = 7;</code>
     * @return The isTop.
     */
    @java.lang.Override
    public boolean getIsTop() {
      return isTop_;
    }
    /**
     * <code>bool is_top = 7;</code>
     * @param value The isTop to set.
     * @return This builder for chaining.
     */
    public Builder setIsTop(boolean value) {

      isTop_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_top = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsTop() {
      bitField0_ = (bitField0_ & ~0x00000040);
      isTop_ = false;
      onChanged();
      return this;
    }

    private boolean mute_ ;
    /**
     * <code>bool mute = 8;</code>
     * @return The mute.
     */
    @java.lang.Override
    public boolean getMute() {
      return mute_;
    }
    /**
     * <code>bool mute = 8;</code>
     * @param value The mute to set.
     * @return This builder for chaining.
     */
    public Builder setMute(boolean value) {

      mute_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool mute = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMute() {
      bitField0_ = (bitField0_ & ~0x00000080);
      mute_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bdsw.msg.SessionInfo)
  }

  // @@protoc_insertion_point(class_scope:com.bdsw.msg.SessionInfo)
  private static final com.bdsw.msg.SessionInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bdsw.msg.SessionInfo();
  }

  public static com.bdsw.msg.SessionInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SessionInfo>
      PARSER = new com.google.protobuf.AbstractParser<SessionInfo>() {
    @java.lang.Override
    public SessionInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SessionInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SessionInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bdsw.msg.SessionInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

