// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ima.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.ima;

/**
 * <pre>
 * 批量推送
 * </pre>
 *
 * Protobuf type {@code com.bdsw.ima.BatchPushRequest}
 */
@com.google.protobuf.Generated
public final class BatchPushRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bdsw.ima.BatchPushRequest)
    BatchPushRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      BatchPushRequest.class.getName());
  }
  // Use BatchPushRequest.newBuilder() to construct.
  private BatchPushRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BatchPushRequest() {
    pushes_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bdsw.ima.ImaProto.internal_static_com_bdsw_ima_BatchPushRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bdsw.ima.ImaProto.internal_static_com_bdsw_ima_BatchPushRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bdsw.ima.BatchPushRequest.class, com.bdsw.ima.BatchPushRequest.Builder.class);
  }

  public static final int PUSHES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.bdsw.ima.PushRequest> pushes_;
  /**
   * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.bdsw.ima.PushRequest> getPushesList() {
    return pushes_;
  }
  /**
   * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.bdsw.ima.PushRequestOrBuilder> 
      getPushesOrBuilderList() {
    return pushes_;
  }
  /**
   * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
   */
  @java.lang.Override
  public int getPushesCount() {
    return pushes_.size();
  }
  /**
   * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
   */
  @java.lang.Override
  public com.bdsw.ima.PushRequest getPushes(int index) {
    return pushes_.get(index);
  }
  /**
   * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
   */
  @java.lang.Override
  public com.bdsw.ima.PushRequestOrBuilder getPushesOrBuilder(
      int index) {
    return pushes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < pushes_.size(); i++) {
      output.writeMessage(1, pushes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < pushes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, pushes_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bdsw.ima.BatchPushRequest)) {
      return super.equals(obj);
    }
    com.bdsw.ima.BatchPushRequest other = (com.bdsw.ima.BatchPushRequest) obj;

    if (!getPushesList()
        .equals(other.getPushesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPushesCount() > 0) {
      hash = (37 * hash) + PUSHES_FIELD_NUMBER;
      hash = (53 * hash) + getPushesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bdsw.ima.BatchPushRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.ima.BatchPushRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.ima.BatchPushRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.ima.BatchPushRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.ima.BatchPushRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.ima.BatchPushRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.ima.BatchPushRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.ima.BatchPushRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bdsw.ima.BatchPushRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bdsw.ima.BatchPushRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bdsw.ima.BatchPushRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.ima.BatchPushRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bdsw.ima.BatchPushRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 批量推送
   * </pre>
   *
   * Protobuf type {@code com.bdsw.ima.BatchPushRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bdsw.ima.BatchPushRequest)
      com.bdsw.ima.BatchPushRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bdsw.ima.ImaProto.internal_static_com_bdsw_ima_BatchPushRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bdsw.ima.ImaProto.internal_static_com_bdsw_ima_BatchPushRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bdsw.ima.BatchPushRequest.class, com.bdsw.ima.BatchPushRequest.Builder.class);
    }

    // Construct using com.bdsw.ima.BatchPushRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (pushesBuilder_ == null) {
        pushes_ = java.util.Collections.emptyList();
      } else {
        pushes_ = null;
        pushesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bdsw.ima.ImaProto.internal_static_com_bdsw_ima_BatchPushRequest_descriptor;
    }

    @java.lang.Override
    public com.bdsw.ima.BatchPushRequest getDefaultInstanceForType() {
      return com.bdsw.ima.BatchPushRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.bdsw.ima.BatchPushRequest build() {
      com.bdsw.ima.BatchPushRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bdsw.ima.BatchPushRequest buildPartial() {
      com.bdsw.ima.BatchPushRequest result = new com.bdsw.ima.BatchPushRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.bdsw.ima.BatchPushRequest result) {
      if (pushesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          pushes_ = java.util.Collections.unmodifiableList(pushes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pushes_ = pushes_;
      } else {
        result.pushes_ = pushesBuilder_.build();
      }
    }

    private void buildPartial0(com.bdsw.ima.BatchPushRequest result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bdsw.ima.BatchPushRequest) {
        return mergeFrom((com.bdsw.ima.BatchPushRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bdsw.ima.BatchPushRequest other) {
      if (other == com.bdsw.ima.BatchPushRequest.getDefaultInstance()) return this;
      if (pushesBuilder_ == null) {
        if (!other.pushes_.isEmpty()) {
          if (pushes_.isEmpty()) {
            pushes_ = other.pushes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePushesIsMutable();
            pushes_.addAll(other.pushes_);
          }
          onChanged();
        }
      } else {
        if (!other.pushes_.isEmpty()) {
          if (pushesBuilder_.isEmpty()) {
            pushesBuilder_.dispose();
            pushesBuilder_ = null;
            pushes_ = other.pushes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            pushesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPushesFieldBuilder() : null;
          } else {
            pushesBuilder_.addAllMessages(other.pushes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.bdsw.ima.PushRequest m =
                  input.readMessage(
                      com.bdsw.ima.PushRequest.parser(),
                      extensionRegistry);
              if (pushesBuilder_ == null) {
                ensurePushesIsMutable();
                pushes_.add(m);
              } else {
                pushesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.bdsw.ima.PushRequest> pushes_ =
      java.util.Collections.emptyList();
    private void ensurePushesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        pushes_ = new java.util.ArrayList<com.bdsw.ima.PushRequest>(pushes_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.bdsw.ima.PushRequest, com.bdsw.ima.PushRequest.Builder, com.bdsw.ima.PushRequestOrBuilder> pushesBuilder_;

    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public java.util.List<com.bdsw.ima.PushRequest> getPushesList() {
      if (pushesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pushes_);
      } else {
        return pushesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public int getPushesCount() {
      if (pushesBuilder_ == null) {
        return pushes_.size();
      } else {
        return pushesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public com.bdsw.ima.PushRequest getPushes(int index) {
      if (pushesBuilder_ == null) {
        return pushes_.get(index);
      } else {
        return pushesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public Builder setPushes(
        int index, com.bdsw.ima.PushRequest value) {
      if (pushesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePushesIsMutable();
        pushes_.set(index, value);
        onChanged();
      } else {
        pushesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public Builder setPushes(
        int index, com.bdsw.ima.PushRequest.Builder builderForValue) {
      if (pushesBuilder_ == null) {
        ensurePushesIsMutable();
        pushes_.set(index, builderForValue.build());
        onChanged();
      } else {
        pushesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public Builder addPushes(com.bdsw.ima.PushRequest value) {
      if (pushesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePushesIsMutable();
        pushes_.add(value);
        onChanged();
      } else {
        pushesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public Builder addPushes(
        int index, com.bdsw.ima.PushRequest value) {
      if (pushesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePushesIsMutable();
        pushes_.add(index, value);
        onChanged();
      } else {
        pushesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public Builder addPushes(
        com.bdsw.ima.PushRequest.Builder builderForValue) {
      if (pushesBuilder_ == null) {
        ensurePushesIsMutable();
        pushes_.add(builderForValue.build());
        onChanged();
      } else {
        pushesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public Builder addPushes(
        int index, com.bdsw.ima.PushRequest.Builder builderForValue) {
      if (pushesBuilder_ == null) {
        ensurePushesIsMutable();
        pushes_.add(index, builderForValue.build());
        onChanged();
      } else {
        pushesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public Builder addAllPushes(
        java.lang.Iterable<? extends com.bdsw.ima.PushRequest> values) {
      if (pushesBuilder_ == null) {
        ensurePushesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pushes_);
        onChanged();
      } else {
        pushesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public Builder clearPushes() {
      if (pushesBuilder_ == null) {
        pushes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        pushesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public Builder removePushes(int index) {
      if (pushesBuilder_ == null) {
        ensurePushesIsMutable();
        pushes_.remove(index);
        onChanged();
      } else {
        pushesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public com.bdsw.ima.PushRequest.Builder getPushesBuilder(
        int index) {
      return internalGetPushesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public com.bdsw.ima.PushRequestOrBuilder getPushesOrBuilder(
        int index) {
      if (pushesBuilder_ == null) {
        return pushes_.get(index);  } else {
        return pushesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public java.util.List<? extends com.bdsw.ima.PushRequestOrBuilder> 
         getPushesOrBuilderList() {
      if (pushesBuilder_ != null) {
        return pushesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pushes_);
      }
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public com.bdsw.ima.PushRequest.Builder addPushesBuilder() {
      return internalGetPushesFieldBuilder().addBuilder(
          com.bdsw.ima.PushRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public com.bdsw.ima.PushRequest.Builder addPushesBuilder(
        int index) {
      return internalGetPushesFieldBuilder().addBuilder(
          index, com.bdsw.ima.PushRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
     */
    public java.util.List<com.bdsw.ima.PushRequest.Builder> 
         getPushesBuilderList() {
      return internalGetPushesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.bdsw.ima.PushRequest, com.bdsw.ima.PushRequest.Builder, com.bdsw.ima.PushRequestOrBuilder> 
        internalGetPushesFieldBuilder() {
      if (pushesBuilder_ == null) {
        pushesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.bdsw.ima.PushRequest, com.bdsw.ima.PushRequest.Builder, com.bdsw.ima.PushRequestOrBuilder>(
                pushes_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        pushes_ = null;
      }
      return pushesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.bdsw.ima.BatchPushRequest)
  }

  // @@protoc_insertion_point(class_scope:com.bdsw.ima.BatchPushRequest)
  private static final com.bdsw.ima.BatchPushRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bdsw.ima.BatchPushRequest();
  }

  public static com.bdsw.ima.BatchPushRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchPushRequest>
      PARSER = new com.google.protobuf.AbstractParser<BatchPushRequest>() {
    @java.lang.Override
    public BatchPushRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BatchPushRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BatchPushRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bdsw.ima.BatchPushRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

