// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ima.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.ima;

@com.google.protobuf.Generated
public interface BatchPushRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.ima.BatchPushRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
   */
  java.util.List<com.bdsw.ima.PushRequest> 
      getPushesList();
  /**
   * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
   */
  com.bdsw.ima.PushRequest getPushes(int index);
  /**
   * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
   */
  int getPushesCount();
  /**
   * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
   */
  java.util.List<? extends com.bdsw.ima.PushRequestOrBuilder> 
      getPushesOrBuilderList();
  /**
   * <code>repeated .com.bdsw.ima.PushRequest pushes = 1;</code>
   */
  com.bdsw.ima.PushRequestOrBuilder getPushesOrBuilder(
      int index);
}
