// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ima.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.ima;

/**
 * <pre>
 * 广播消息
 * </pre>
 *
 * Protobuf type {@code com.bdsw.ima.BroadcastMessage}
 */
@com.google.protobuf.Generated
public final class BroadcastMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bdsw.ima.BroadcastMessage)
    BroadcastMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      BroadcastMessage.class.getName());
  }
  // Use BroadcastMessage.newBuilder() to construct.
  private BroadcastMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BroadcastMessage() {
    targetUsers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bdsw.ima.ImaProto.internal_static_com_bdsw_ima_BroadcastMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bdsw.ima.ImaProto.internal_static_com_bdsw_ima_BroadcastMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bdsw.ima.BroadcastMessage.class, com.bdsw.ima.BroadcastMessage.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGE_FIELD_NUMBER = 1;
  private com.bdsw.common.ServerMessage message_;
  /**
   * <code>.com.bdsw.common.ServerMessage message = 1;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.bdsw.common.ServerMessage message = 1;</code>
   * @return The message.
   */
  @java.lang.Override
  public com.bdsw.common.ServerMessage getMessage() {
    return message_ == null ? com.bdsw.common.ServerMessage.getDefaultInstance() : message_;
  }
  /**
   * <code>.com.bdsw.common.ServerMessage message = 1;</code>
   */
  @java.lang.Override
  public com.bdsw.common.ServerMessageOrBuilder getMessageOrBuilder() {
    return message_ == null ? com.bdsw.common.ServerMessage.getDefaultInstance() : message_;
  }

  public static final int TARGET_USERS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList targetUsers_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 空表示广播给所有人
   * </pre>
   *
   * <code>repeated string target_users = 2;</code>
   * @return A list containing the targetUsers.
   */
  public com.google.protobuf.ProtocolStringList
      getTargetUsersList() {
    return targetUsers_;
  }
  /**
   * <pre>
   * 空表示广播给所有人
   * </pre>
   *
   * <code>repeated string target_users = 2;</code>
   * @return The count of targetUsers.
   */
  public int getTargetUsersCount() {
    return targetUsers_.size();
  }
  /**
   * <pre>
   * 空表示广播给所有人
   * </pre>
   *
   * <code>repeated string target_users = 2;</code>
   * @param index The index of the element to return.
   * @return The targetUsers at the given index.
   */
  public java.lang.String getTargetUsers(int index) {
    return targetUsers_.get(index);
  }
  /**
   * <pre>
   * 空表示广播给所有人
   * </pre>
   *
   * <code>repeated string target_users = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the targetUsers at the given index.
   */
  public com.google.protobuf.ByteString
      getTargetUsersBytes(int index) {
    return targetUsers_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMessage());
    }
    for (int i = 0; i < targetUsers_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, targetUsers_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMessage());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < targetUsers_.size(); i++) {
        dataSize += computeStringSizeNoTag(targetUsers_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTargetUsersList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bdsw.ima.BroadcastMessage)) {
      return super.equals(obj);
    }
    com.bdsw.ima.BroadcastMessage other = (com.bdsw.ima.BroadcastMessage) obj;

    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
          .equals(other.getMessage())) return false;
    }
    if (!getTargetUsersList()
        .equals(other.getTargetUsersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    if (getTargetUsersCount() > 0) {
      hash = (37 * hash) + TARGET_USERS_FIELD_NUMBER;
      hash = (53 * hash) + getTargetUsersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bdsw.ima.BroadcastMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.ima.BroadcastMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.ima.BroadcastMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.ima.BroadcastMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.ima.BroadcastMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.ima.BroadcastMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.ima.BroadcastMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.ima.BroadcastMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bdsw.ima.BroadcastMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bdsw.ima.BroadcastMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bdsw.ima.BroadcastMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.ima.BroadcastMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bdsw.ima.BroadcastMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 广播消息
   * </pre>
   *
   * Protobuf type {@code com.bdsw.ima.BroadcastMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bdsw.ima.BroadcastMessage)
      com.bdsw.ima.BroadcastMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bdsw.ima.ImaProto.internal_static_com_bdsw_ima_BroadcastMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bdsw.ima.ImaProto.internal_static_com_bdsw_ima_BroadcastMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bdsw.ima.BroadcastMessage.class, com.bdsw.ima.BroadcastMessage.Builder.class);
    }

    // Construct using com.bdsw.ima.BroadcastMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetMessageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      targetUsers_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bdsw.ima.ImaProto.internal_static_com_bdsw_ima_BroadcastMessage_descriptor;
    }

    @java.lang.Override
    public com.bdsw.ima.BroadcastMessage getDefaultInstanceForType() {
      return com.bdsw.ima.BroadcastMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.bdsw.ima.BroadcastMessage build() {
      com.bdsw.ima.BroadcastMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bdsw.ima.BroadcastMessage buildPartial() {
      com.bdsw.ima.BroadcastMessage result = new com.bdsw.ima.BroadcastMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bdsw.ima.BroadcastMessage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.message_ = messageBuilder_ == null
            ? message_
            : messageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        targetUsers_.makeImmutable();
        result.targetUsers_ = targetUsers_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bdsw.ima.BroadcastMessage) {
        return mergeFrom((com.bdsw.ima.BroadcastMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bdsw.ima.BroadcastMessage other) {
      if (other == com.bdsw.ima.BroadcastMessage.getDefaultInstance()) return this;
      if (other.hasMessage()) {
        mergeMessage(other.getMessage());
      }
      if (!other.targetUsers_.isEmpty()) {
        if (targetUsers_.isEmpty()) {
          targetUsers_ = other.targetUsers_;
          bitField0_ |= 0x00000002;
        } else {
          ensureTargetUsersIsMutable();
          targetUsers_.addAll(other.targetUsers_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTargetUsersIsMutable();
              targetUsers_.add(s);
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.bdsw.common.ServerMessage message_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bdsw.common.ServerMessage, com.bdsw.common.ServerMessage.Builder, com.bdsw.common.ServerMessageOrBuilder> messageBuilder_;
    /**
     * <code>.com.bdsw.common.ServerMessage message = 1;</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.bdsw.common.ServerMessage message = 1;</code>
     * @return The message.
     */
    public com.bdsw.common.ServerMessage getMessage() {
      if (messageBuilder_ == null) {
        return message_ == null ? com.bdsw.common.ServerMessage.getDefaultInstance() : message_;
      } else {
        return messageBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.bdsw.common.ServerMessage message = 1;</code>
     */
    public Builder setMessage(com.bdsw.common.ServerMessage value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        message_ = value;
      } else {
        messageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.ServerMessage message = 1;</code>
     */
    public Builder setMessage(
        com.bdsw.common.ServerMessage.Builder builderForValue) {
      if (messageBuilder_ == null) {
        message_ = builderForValue.build();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.ServerMessage message = 1;</code>
     */
    public Builder mergeMessage(com.bdsw.common.ServerMessage value) {
      if (messageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          message_ != null &&
          message_ != com.bdsw.common.ServerMessage.getDefaultInstance()) {
          getMessageBuilder().mergeFrom(value);
        } else {
          message_ = value;
        }
      } else {
        messageBuilder_.mergeFrom(value);
      }
      if (message_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.bdsw.common.ServerMessage message = 1;</code>
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      message_ = null;
      if (messageBuilder_ != null) {
        messageBuilder_.dispose();
        messageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.ServerMessage message = 1;</code>
     */
    public com.bdsw.common.ServerMessage.Builder getMessageBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.bdsw.common.ServerMessage message = 1;</code>
     */
    public com.bdsw.common.ServerMessageOrBuilder getMessageOrBuilder() {
      if (messageBuilder_ != null) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        return message_ == null ?
            com.bdsw.common.ServerMessage.getDefaultInstance() : message_;
      }
    }
    /**
     * <code>.com.bdsw.common.ServerMessage message = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bdsw.common.ServerMessage, com.bdsw.common.ServerMessage.Builder, com.bdsw.common.ServerMessageOrBuilder> 
        internalGetMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bdsw.common.ServerMessage, com.bdsw.common.ServerMessage.Builder, com.bdsw.common.ServerMessageOrBuilder>(
                getMessage(),
                getParentForChildren(),
                isClean());
        message_ = null;
      }
      return messageBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList targetUsers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTargetUsersIsMutable() {
      if (!targetUsers_.isModifiable()) {
        targetUsers_ = new com.google.protobuf.LazyStringArrayList(targetUsers_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <pre>
     * 空表示广播给所有人
     * </pre>
     *
     * <code>repeated string target_users = 2;</code>
     * @return A list containing the targetUsers.
     */
    public com.google.protobuf.ProtocolStringList
        getTargetUsersList() {
      targetUsers_.makeImmutable();
      return targetUsers_;
    }
    /**
     * <pre>
     * 空表示广播给所有人
     * </pre>
     *
     * <code>repeated string target_users = 2;</code>
     * @return The count of targetUsers.
     */
    public int getTargetUsersCount() {
      return targetUsers_.size();
    }
    /**
     * <pre>
     * 空表示广播给所有人
     * </pre>
     *
     * <code>repeated string target_users = 2;</code>
     * @param index The index of the element to return.
     * @return The targetUsers at the given index.
     */
    public java.lang.String getTargetUsers(int index) {
      return targetUsers_.get(index);
    }
    /**
     * <pre>
     * 空表示广播给所有人
     * </pre>
     *
     * <code>repeated string target_users = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the targetUsers at the given index.
     */
    public com.google.protobuf.ByteString
        getTargetUsersBytes(int index) {
      return targetUsers_.getByteString(index);
    }
    /**
     * <pre>
     * 空表示广播给所有人
     * </pre>
     *
     * <code>repeated string target_users = 2;</code>
     * @param index The index to set the value at.
     * @param value The targetUsers to set.
     * @return This builder for chaining.
     */
    public Builder setTargetUsers(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTargetUsersIsMutable();
      targetUsers_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 空表示广播给所有人
     * </pre>
     *
     * <code>repeated string target_users = 2;</code>
     * @param value The targetUsers to add.
     * @return This builder for chaining.
     */
    public Builder addTargetUsers(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTargetUsersIsMutable();
      targetUsers_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 空表示广播给所有人
     * </pre>
     *
     * <code>repeated string target_users = 2;</code>
     * @param values The targetUsers to add.
     * @return This builder for chaining.
     */
    public Builder addAllTargetUsers(
        java.lang.Iterable<java.lang.String> values) {
      ensureTargetUsersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, targetUsers_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 空表示广播给所有人
     * </pre>
     *
     * <code>repeated string target_users = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetUsers() {
      targetUsers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 空表示广播给所有人
     * </pre>
     *
     * <code>repeated string target_users = 2;</code>
     * @param value The bytes of the targetUsers to add.
     * @return This builder for chaining.
     */
    public Builder addTargetUsersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTargetUsersIsMutable();
      targetUsers_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bdsw.ima.BroadcastMessage)
  }

  // @@protoc_insertion_point(class_scope:com.bdsw.ima.BroadcastMessage)
  private static final com.bdsw.ima.BroadcastMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bdsw.ima.BroadcastMessage();
  }

  public static com.bdsw.ima.BroadcastMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BroadcastMessage>
      PARSER = new com.google.protobuf.AbstractParser<BroadcastMessage>() {
    @java.lang.Override
    public BroadcastMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BroadcastMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BroadcastMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bdsw.ima.BroadcastMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

