// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ima.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.ima;

@com.google.protobuf.Generated
public interface BroadcastMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.ima.BroadcastMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.bdsw.common.ServerMessage message = 1;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.com.bdsw.common.ServerMessage message = 1;</code>
   * @return The message.
   */
  com.bdsw.common.ServerMessage getMessage();
  /**
   * <code>.com.bdsw.common.ServerMessage message = 1;</code>
   */
  com.bdsw.common.ServerMessageOrBuilder getMessageOrBuilder();

  /**
   * <pre>
   * 空表示广播给所有人
   * </pre>
   *
   * <code>repeated string target_users = 2;</code>
   * @return A list containing the targetUsers.
   */
  java.util.List<java.lang.String>
      getTargetUsersList();
  /**
   * <pre>
   * 空表示广播给所有人
   * </pre>
   *
   * <code>repeated string target_users = 2;</code>
   * @return The count of targetUsers.
   */
  int getTargetUsersCount();
  /**
   * <pre>
   * 空表示广播给所有人
   * </pre>
   *
   * <code>repeated string target_users = 2;</code>
   * @param index The index of the element to return.
   * @return The targetUsers at the given index.
   */
  java.lang.String getTargetUsers(int index);
  /**
   * <pre>
   * 空表示广播给所有人
   * </pre>
   *
   * <code>repeated string target_users = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the targetUsers at the given index.
   */
  com.google.protobuf.ByteString
      getTargetUsersBytes(int index);
}
