// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ima.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.ima;

@com.google.protobuf.Generated
public final class ImaProto extends com.google.protobuf.GeneratedFile {
  private ImaProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      ImaProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_ima_PushRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_ima_PushRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_ima_BatchPushRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_ima_BatchPushRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_ima_BroadcastMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_ima_BroadcastMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_ima_KickUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_ima_KickUserRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tima.proto\022\014com.bdsw.ima\032\014common.proto\"" +
      "b\n\013PushRequest\022\017\n\007user_id\030\001 \001(\t\022\021\n\tdevic" +
      "e_id\030\002 \001(\t\022/\n\007message\030\003 \001(\0132\036.com.bdsw.c" +
      "ommon.ServerMessage\"=\n\020BatchPushRequest\022" +
      ")\n\006pushes\030\001 \003(\0132\031.com.bdsw.ima.PushReque" +
      "st\"Y\n\020BroadcastMessage\022/\n\007message\030\001 \001(\0132" +
      "\036.com.bdsw.common.ServerMessage\022\024\n\014targe" +
      "t_users\030\002 \003(\t\"W\n\017KickUserRequest\022\017\n\007user" +
      "_id\030\001 \001(\t\022\021\n\tdevice_id\030\002 \001(\t\022\016\n\006reason\030\003" +
      " \001(\t\022\020\n\010operator\030\004 \001(\t2\300\002\n\nImaService\022H\n" +
      "\nPushToUser\022\031.com.bdsw.ima.PushRequest\032\035" +
      ".com.bdsw.common.BaseResponse\"\000\022N\n\013PushT" +
      "oUsers\022\036.com.bdsw.ima.BatchPushRequest\032\035" +
      ".com.bdsw.common.BaseResponse\"\000\022L\n\tBroad" +
      "cast\022\036.com.bdsw.ima.BroadcastMessage\032\035.c" +
      "om.bdsw.common.BaseResponse\"\000\022J\n\010KickUse" +
      "r\022\035.com.bdsw.ima.KickUserRequest\032\035.com.b" +
      "dsw.common.BaseResponse\"\000BB\n\014com.bdsw.im" +
      "aB\010ImaProtoP\001Z&github.com/bdsw/bdsw-im-w" +
      "s/api/ima;imab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.bdsw.common.CommonProto.getDescriptor(),
        });
    internal_static_com_bdsw_ima_PushRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bdsw_ima_PushRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_ima_PushRequest_descriptor,
        new java.lang.String[] { "UserId", "DeviceId", "Message", });
    internal_static_com_bdsw_ima_BatchPushRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bdsw_ima_BatchPushRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_ima_BatchPushRequest_descriptor,
        new java.lang.String[] { "Pushes", });
    internal_static_com_bdsw_ima_BroadcastMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_bdsw_ima_BroadcastMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_ima_BroadcastMessage_descriptor,
        new java.lang.String[] { "Message", "TargetUsers", });
    internal_static_com_bdsw_ima_KickUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_bdsw_ima_KickUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_ima_KickUserRequest_descriptor,
        new java.lang.String[] { "UserId", "DeviceId", "Reason", "Operator", });
    descriptor.resolveAllFeaturesImmutable();
    com.bdsw.common.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
