// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ima.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.ima;

@com.google.protobuf.Generated
public interface KickUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.ima.KickUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string device_id = 2;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 2;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <pre>
   * multi_login, admin_kick, system_maintenance
   * </pre>
   *
   * <code>string reason = 3;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <pre>
   * multi_login, admin_kick, system_maintenance
   * </pre>
   *
   * <code>string reason = 3;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>string operator = 4;</code>
   * @return The operator.
   */
  java.lang.String getOperator();
  /**
   * <code>string operator = 4;</code>
   * @return The bytes for operator.
   */
  com.google.protobuf.ByteString
      getOperatorBytes();
}
