// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ima.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.ima;

@com.google.protobuf.Generated
public interface PushRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.ima.PushRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string device_id = 2;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 2;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>.com.bdsw.common.ServerMessage message = 3;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.com.bdsw.common.ServerMessage message = 3;</code>
   * @return The message.
   */
  com.bdsw.common.ServerMessage getMessage();
  /**
   * <code>.com.bdsw.common.ServerMessage message = 3;</code>
   */
  com.bdsw.common.ServerMessageOrBuilder getMessageOrBuilder();
}
